use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    time::{SystemTime, UNIX_EPOCH},
};

use skeleton_new::{Checkout, ProjectName, Source, format_project, generate};

struct TempDir(PathBuf);

impl TempDir {
    fn new(label: &str) -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "skeleton-new-test-{label}-{}-{nanos}",
            std::process::id()
        ));
        fs::create_dir_all(&path).unwrap();
        Self(path)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn git(directory: &Path, args: &[&str]) {
    let output = Command::new("git")
        .args([
            "-c",
            "user.name=test",
            "-c",
            "user.email=test@example.com",
            "-c",
            "commit.gpgsign=false",
        ])
        .args(args)
        .current_dir(directory)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {args:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn write(root: &Path, relative: &str, contents: &str) {
    let path = root.join(relative);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, contents).unwrap();
}

const LOCK: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"alpha\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\n\n[[package]]\nname = \"base_skeleton_rust\"\nversion = \"0.1.0\"\ndependencies = [\n \"alpha\",\n]\n\n[[package]]\nname = \"zeta\"\nversion = \"2.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\n";

/// A small git repository shaped like the skeleton: renamable names, a lockfile,
/// a script, this tool's own directory, an ignored secret, and a `feature` branch.
struct Skeleton {
    _temp: TempDir,
    url: String,
}

impl Skeleton {
    fn new() -> Self {
        let temp = TempDir::new("skeleton");
        let root = temp.0.join("skeleton");
        fs::create_dir_all(&root).unwrap();
        git(&root, &["init", "--quiet", "-b", "main"]);

        write(&root, ".gitignore", ".env\ntarget/\n");
        write(&root, ".env", "SECRET=do-not-copy\n");
        write(
            &root,
            "Cargo.toml",
            "[package]\nname = \"base_skeleton_rust\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        );
        write(&root, "Cargo.lock", LOCK);
        write(
            &root,
            "src/main.rs",
            "use base_skeleton_rust::run;\nuse std::io;\n\nfn main() {\n    let _ = io::stdout();\n    run();\n}\n",
        );
        write(&root, "src/lib.rs", "pub fn run() {}\n");
        write(
            &root,
            ".env.example",
            "DATABASE_URL=postgres://localhost/base_skeleton\nOTEL_SERVICE_NAME=base-skeleton-rust\n",
        );
        write(&root, "docs/guide.md", "audience: base-skeleton-api\n");
        write(&root, "scaffold/notes.md", "tool internals\n");
        write(&root, "scripts/run.sh", "#!/bin/sh\necho base_skeleton\n");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(
                root.join("scripts/run.sh"),
                fs::Permissions::from_mode(0o755),
            )
            .unwrap();
        }
        git(&root, &["add", "-A"]);
        git(&root, &["commit", "--quiet", "-m", "skeleton"]);

        git(&root, &["checkout", "--quiet", "-b", "feature"]);
        write(&root, "FEATURE.txt", "only on the feature branch\n");
        git(&root, &["add", "-A"]);
        git(&root, &["commit", "--quiet", "-m", "feature"]);
        git(&root, &["checkout", "--quiet", "main"]);

        let url = format!("file://{}", root.display());
        Self { _temp: temp, url }
    }

    fn source(&self) -> Source<'_> {
        Source {
            repo: &self.url,
            reference: None,
        }
    }
}

fn files_under(root: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let mut pending = vec![root.to_path_buf()];
    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(directory).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                pending.push(path);
            } else {
                found.push(path);
            }
        }
    }
    found.sort();
    found
}

fn relative_names(root: &Path) -> Vec<String> {
    files_under(root)
        .iter()
        .map(|file| {
            file.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .into_owned()
        })
        .collect()
}

fn project(name: &str) -> ProjectName {
    ProjectName::parse(name).unwrap()
}

#[test]
fn renames_every_skeleton_spelling_and_copies_only_tracked_project_files() {
    let skeleton = Skeleton::new();
    let output = TempDir::new("out");
    let generated = generate(&project("orders-api"), &output.0, skeleton.source()).unwrap();

    assert!(!generated.revision.is_empty());
    let names = relative_names(&generated.directory);
    assert_eq!(names.len(), generated.files);
    for expected in [
        ".env.example",
        ".gitignore",
        "Cargo.lock",
        "Cargo.toml",
        "docs/guide.md",
        "scripts/run.sh",
        "src/lib.rs",
        "src/main.rs",
    ] {
        assert!(
            names.iter().any(|name| name == expected),
            "missing {expected}"
        );
    }
    // Ignored secrets, git metadata and this tool's own directory never appear.
    for name in &names {
        assert!(name != ".env", "{name} must not be generated");
        assert!(
            !name.starts_with(".git/") && !name.starts_with("scaffold/"),
            "{name} must not be generated"
        );
    }

    for file in files_under(&generated.directory) {
        let text = fs::read_to_string(&file).unwrap();
        for needle in ["base_skeleton", "base-skeleton"] {
            assert!(
                !text.contains(needle),
                "{} contains {needle}",
                file.display()
            );
        }
    }
    let read = |relative: &str| fs::read_to_string(generated.directory.join(relative)).unwrap();
    assert!(read("Cargo.toml").contains("name = \"orders_api\""));
    assert!(read(".env.example").contains("/orders_api\n"));
    assert!(read(".env.example").contains("OTEL_SERVICE_NAME=orders-api\n"));
    assert_eq!(read("docs/guide.md"), "audience: orders-api-api\n");
}

#[test]
fn generated_lockfile_keeps_cargo_package_order() {
    let skeleton = Skeleton::new();
    for name in ["zebra", "aardvark", "mid"] {
        let output = TempDir::new("lock");
        let generated = generate(&project(name), &output.0, skeleton.source()).unwrap();
        let lock = fs::read_to_string(generated.directory.join("Cargo.lock")).unwrap();
        let names: Vec<&str> = lock
            .lines()
            .filter_map(|line| line.strip_prefix("name = \""))
            .map(|rest| rest.trim_end_matches('"'))
            .collect();
        assert!(names.contains(&name), "{name}: {names:?}");
        assert!(
            names.windows(2).all(|pair| pair[0] <= pair[1]),
            "{name}: packages are not sorted: {names:?}"
        );
    }
}

#[cfg(unix)]
#[test]
fn keeps_the_executable_bit_of_scripts() {
    use std::os::unix::fs::PermissionsExt;

    let skeleton = Skeleton::new();
    let output = TempDir::new("mode");
    let generated = generate(&project("orders-api"), &output.0, skeleton.source()).unwrap();
    let mode = fs::metadata(generated.directory.join("scripts/run.sh"))
        .unwrap()
        .permissions()
        .mode();
    assert_eq!(mode & 0o111, 0o111);
}

#[test]
fn fetches_the_requested_branch_instead_of_the_default() {
    let skeleton = Skeleton::new();
    let default = TempDir::new("default");
    let on_default = generate(&project("orders-api"), &default.0, skeleton.source()).unwrap();
    assert!(!on_default.directory.join("FEATURE.txt").exists());

    let branch = TempDir::new("branch");
    let source = Source {
        reference: Some("feature"),
        ..skeleton.source()
    };
    let on_feature = generate(&project("orders-api"), &branch.0, source).unwrap();
    assert!(on_feature.directory.join("FEATURE.txt").is_file());
    assert_ne!(on_default.revision, on_feature.revision);
}

#[test]
fn a_missing_branch_or_repository_fails_without_creating_the_project() {
    let skeleton = Skeleton::new();
    let output = TempDir::new("missing");

    let source = Source {
        reference: Some("no-such-branch"),
        ..skeleton.source()
    };
    let error = generate(&project("orders-api"), &output.0, source).unwrap_err();
    assert!(format!("{error:#}").contains("no-such-branch"), "{error:#}");

    let source = Source {
        repo: "file:///definitely/not/a/repository",
        reference: None,
    };
    assert!(generate(&project("orders-api"), &output.0, source).is_err());
    assert!(!output.0.join("orders-api").exists());
}

#[test]
fn refuses_a_non_empty_directory_before_fetching_anything() {
    let temp = TempDir::new("occupied");
    let occupied = temp.0.join("orders-api");
    fs::create_dir_all(&occupied).unwrap();
    fs::write(occupied.join("keep.txt"), "mine").unwrap();

    // The repository does not exist: only the up-front target check can explain
    // this error, which proves nothing was fetched.
    let source = Source {
        repo: "file:///definitely/not/a/repository",
        reference: None,
    };
    let error = generate(&project("orders-api"), &temp.0, source).unwrap_err();
    assert!(error.to_string().contains("not empty"), "{error}");
    assert_eq!(files_under(&occupied).len(), 1);
}

#[test]
fn accepts_an_existing_empty_directory() {
    let skeleton = Skeleton::new();
    let temp = TempDir::new("empty");
    fs::create_dir_all(temp.0.join("orders-api")).unwrap();
    generate(&project("orders-api"), &temp.0, skeleton.source()).unwrap();
    assert!(temp.0.join("orders-api/Cargo.toml").is_file());
}

#[test]
fn the_temporary_checkout_is_removed_when_dropped() {
    let skeleton = Skeleton::new();
    let checkout = Checkout::fetch(skeleton.source()).unwrap();
    let directory = checkout.directory().to_path_buf();
    assert!(directory.join("Cargo.toml").is_file());
    drop(checkout);
    assert!(!directory.exists());
}

#[test]
fn formatting_makes_the_renamed_sources_pass_cargo_fmt_check() {
    let skeleton = Skeleton::new();
    let output = TempDir::new("fmt");
    // `zz_app` sorts after `std`, so the renamed import order is no longer rustfmt's.
    let generated = generate(&project("zz-app"), &output.0, skeleton.source()).unwrap();
    let check = |directory: &Path| {
        Command::new("cargo")
            .args(["fmt", "--all", "--", "--check"])
            .current_dir(directory)
            .output()
            .unwrap()
            .status
            .success()
    };
    assert!(
        !check(&generated.directory),
        "the rename should need formatting"
    );
    format_project(&generated.directory).unwrap();
    assert!(check(&generated.directory));
}
